---
#Creates admissions

apiVersion: admissionregistration/v1
kind: ValidatingWebhookConfiguration
metadata: 
  name: "pod-policy.example.com"

webhooks:

- name: "pod-policy.example.com"
  clientConfig: 
    url: "<external url>"
    
  rules: 
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE"]
      resources:   ["pods"]
      scope:       "Namespaced"