---
#Creates a service account for nginx ingress controller

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
  annotations:
    e

# need to create roles, clusterroles, rolebindings