apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    release: prometheus
    team: frontend
spec:
  selector:
    matchLabels:
      app: web
  endpoints:
  - port: web