#Creates a ns for kandula

apiVersion: v1
kind: Namespace
metadata:
  name: kandula

---
#Creates a configMap to use variables

apiVersion: v1
kind: ConfigMap
metadata:
  name: kandula-config
  namespace: kandula
data:
  FLASK_APP: "run.py"
  FLASK_DEBUG: "1"
#  APP_COLOR: green
  


---
#Creates a configMap to use variables

#apiVersion: v1
#kind: Secret
#metadata:
#  name: kandula-secret
#  namespace: kandula
#data:
  

#envFrom:
#  - secretRef:
#      name: <secret name>

---
# Creates a deplyoment with kandula pod container

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kandula-app
  namespace: kandula
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kandula-app
  template:
    metadata:
      labels:
        app: kandula-app
    spec:
      containers:
      - name: kandula-app
        image: public.ecr.aws/t9x8t6s4/kandula-pub:latest
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
                name: kandula-config
                
---
#Exposing the pod to access the app using a web browser

apiVersion: v1
kind: Service
metadata:
  name: kandula-service
  namespace: kandula
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
  selector:
    app: kandula-app
