---
# Creates headless service for postgres

apiVersion: v1
kind: Service
metadata:
  name: postgres-service-headles
  namespace: kandula
spec:
  clusterIP: None
  ports:
  - port: 5432
  selector:
    db: postgres
  