---
# Creates a statefulset for postgres db

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: kandula
  labels:
    app: postgres
spec:
  serviceName: postgres-service-headles
  replicas: 3
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: 
      containers:
      - name: postgres
        image: postgres
        volumeMounts:
        - mountPath: 
          name: 

volumeClaimTemplates:
- metadata:
    name: postgres-pvc
  spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-storage
  resources:
    requests:
      storage: 5Gi
