---
# Creates a persistent volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
   storage: 10Gi
  awsElasticBlockStore:
    volumeID: 
    fsType: 