---
# Creates nodeport service for postgres app

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: kandula
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5432
    nodePort: 30002
  selector:
    db: postgres