---
# Creates a storage class

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-storage
provisioner: kubernetes.io/aws-pd
parameters:
  type: pd-standard
  replication-type: none