---
#Creates a secret file to use variables

apiVersion: v1
kind: Secret
metadata:
  name: kandula-secret
  namespace: kandula
data:
  AWS_ACCESS_KEY_ID: QUtJQTJXVjZFQ09WM05VVU4yNlk=
  AWS_SECRET_ACCESS_KEY: K2R3MDJuSDZ5a3pGcUdPb2ZuRXdLV0p2Q3RlMWVDb1NBQjRHRGlGag==
  