#Creating a configMap to use variables

apiVersion: v1
kind: ConfigMap
metadata:
  name: kandula-config
  namespace: kandula
data:
  FLASK_APP: "run.py"
  FLASK_DEBUG: "1"
  APP_COLOR: green

---
# Creating a deplyoment with kandula pod container

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kandula-app
  namespace: kandula
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kandula-app
  template:
    metadata:
      labels:
        app: kandula-app
    spec:
      serviceAccountName: opsschool-sa
      containers:
      - name: kandula-app
        image: 735911875499.dkr.ecr.us-east-1.amazonaws.com/kandula:latest
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
                name: kandula-config
        
---
#Exposing the pod to access the app using a web browser

apiVersion: v1
kind: Service
metadata:
  name: kandula-service
  namespace: kandula
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: kandula-app
