---
# Creates a cron job

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kandula-app-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
           containers:
             - name: 
               image: 
               command:
           restartPoilcy: Never