---
# Creates a job

apiVersion: batch/v1
kind: Job
metadata:
  name: kandula-app-job
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
       containers:
         - name: 
           image: 
           command:
       restartPoilcy: Never