<<<<<<< HEAD
#Create a namespace for kandula

=======
>>>>>>> eea24739882c5550f9fff3ad4e1b5a0e21cbbb40
apiVersion: v1
kind: Namespace
metadata:
  name: kandula
<<<<<<< HEAD


---
#Creates a secret file to use variables

apiVersion: v1
kind: Secret
metadata:
  name: kandula-secret
  namespace: kandula
data:
  AWS_ACCESS_KEY_ID: QUtJQTJXVjZFQ09WM05VVU4yNlk=
  AWS_SECRET_ACCESS_KEY: K2R3MDJuSDZ5a3pGcUdPb2ZuRXdLV0p2Q3RlMWVDb1NBQjRHRGlGag==

---

#Creates a configMap to use variables
=======
  
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kandula-sa
  namespace: kandula
  annotations:
    eks.amazonaws.com/role-arn-with-oidc: arn:aws:iam::735911875499:role/
    eks.amazonaws.com/role-arn-sa-eks-role: arn:aws:iam::735911875499:role/opsschool-project-sa-eks-role
>>>>>>> eea24739882c5550f9fff3ad4e1b5a0e21cbbb40

---
#Creating a configMap to use variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: kandula-config
  namespace: kandula
data:
  FLASK_APP: "run.py"
  FLASK_DEBUG: "1"

---
# Creating a deplyoment with kandula pod container

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kandula-app
  namespace: kandula
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kandula-app
  template:
    metadata:
      labels:
        app: kandula-app
    spec:
      serviceAccountName: opsschool-sa
      containers:
      - name: kandula-app
        image: 735911875499.dkr.ecr.us-east-1.amazonaws.com/kandula:latest
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
                name: kandula-config
          - secretRef:
                name: kandula-secret
        
---
#Exposing the pod to access the app using a web browser

apiVersion: v1
kind: Service
metadata:
  name: kandula-service
  namespace: kandula
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: kandula-app

----
#Creates HPA for memory and CPU

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kandula-hpa
  namespace: kandula
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kandula-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
