---
# Creates editor role for accessing kandula pod

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kandula
  name: pod-editor
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]
#  resourceNames: []