---
# This cluster role binding allows anyone in the "manager" group to read nginx ingress

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-ingress-global
subjects:
- kind: Group
  name: manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ingress-read
  apiGroup: rbac.authorization.k8s.io