apiVersion: v1
kind: Namespace
metadata:
  name: kandula

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kandula-config
  namespace: kandula
data:
  FLASK_APP: "run.py"
  FLASK_DEBUG: "1"
  AWS_ACCESS_KEY_ID: QUtJQTJXVjZFQ09WM05VVU4yNlk=
  AWS_SECRET_ACCESS_KEY: K2R3MDJuSDZ5a3pGcUdPb2ZuRXdLV0p2Q3RlMWVDb1NBQjRHRGlGag==

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kandula-sa
  namespace: kandula
  annotations:
    eks.amazonaws.com/role-arn-sa-eks-role: arn:aws:iam::735911875499:role/opsschool-project-sa

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kandula-app
  namespace: kandula
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kandula-app
  template:
    metadata:
      labels:
        app: kandula-app
    spec:
      serviceAccountName: kandula-sa
      containers:
      - name: kandula-app
        image: public.ecr.aws/t9x8t6s4/kandula-pub:21
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: kandula-config

---

apiVersion: v1
kind: Service
metadata:
  name: kandula-service
  namespace: kandula
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
  selector:
    app: kandula-app

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kandula-hpa
  namespace: kandula
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kandula-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
